### ISSUE TITLE
Have to reapply dimmer on every page load, page refresh and new tab, etc.

### ISSUE THREAD

**Issue by highab** [mehmetb/dimmer#2]
Hi, this looks like it's just what I was looking for in that it dims the screen nicely if I click on any link or refresh the page it turns off and I have to reapply it... which is both frustrating and painful... flashes of white where there was once grey.

Is this the desired effect?

**Comment by mehmetb** [comment]
Hi, no it's not desired. In the first release I tried to overcome this issue but I wasn't able to find a way that doesn't require a permission. I will have a look at it again today and let you know :)

**Comment by mehmetb** [comment]
It turns out there is no way to execute a script inside a tab after a page reload (without a special permission). I will implement this and bump the major version but the extension will require 'Read/write all websites' permission from now on :/

**Comment by highab** [comment]
Thanks!

Ali High
highab@dplanet.ch
highab
+41794190413


On 14 November 2020, 11:34, Mehmet Baker wrote:

It turns out there is no way to execute a script inside a tab after a page reload (without a special permission). I will implement this and bump the major version but the extension will require 'Read/write all websites' permission from now on :/
