### ISSUE TITLE
Add ability to turn "Only for this tab" switch on by default

### ISSUE THREAD

**Issue by Andrew15-5** [mehmetb/dimmer#21]
I think this is the only dimmer extension in existence for Firefox. Despite it being very simple and easy to use, I hate that it automatically would dim all the tabs when I hit the dim shortcut. To prevent this, I have to click on the extension icon and tick the "Only for this tab" on every single tab where I want to dim only it and not everything else. It seems that dim level is saved when it is changed, but the "Only for this tab" checkbox is not.

There are 2 solutions: either make the checkbox remember its state when user change it, or add a second button to "Dim only this tab" + a second shortcut that will do exactly that would be a blessing.

**Comment by mehmetb** [comment]
Thank you for the feature request @Andrew15-5, I'm working on it 👍

**Comment by mehmetb** [comment]
Hi @Andrew15-5, Version 3.1.0 is available now. I added a Default Settings button in the pop-up. When you open your browser just choose 'The active tab only' in the default settings. The new tabs will have their own states after that point and will not be dimmed when you dim a tab. You can read more here: https://github.com/mehmetb/dimmer#default-settings

**Comment by mehmetb** [comment]
@Andrew15-5 Unfortunately settings are not saved. You will have to set the Default Settings every time you open your browser. 

I started working on the next version, which will also support dimming PDF pages. The add-on will also remember its state so you won't have to update the settings every time you open the browser.

**Comment by Andrew15-5** [comment]
> Unfortunately settings are not saved. You will have to set the Default Settings every time you open your browser.

Well, then I have to **not** close my browser. I do keep at least 1 tab at all times, so I rarely had this session storage wipe (some cookies are removed after all browser tabs are closed). But yeah, I will wait for the proper persistent settings.

I already updated it. Looks good. I will still have to test how much better it is now. Thanks.

BTW, will the second shortcut be implemented in the future? So that I don't even need to open the settings if "shortcuts" way is better for me. Because I only really use keyboard 90% of the time. And if there is a dedicated this-tab-only shortcut, then I wouldn't have to worry about settings not being saved (until the next update anyway).

**Comment by mehmetb** [comment]
> I already updated it. Looks good. I will still have to test how much better it is now. Thanks.

Good to hear that it is working, no problem at all. It is now more useful to me as well :)




> BTW, will the second shortcut be implemented in the future? So that I don't even need to open the settings if "shortcuts" way is better for me. Because I only really use keyboard 90% of the time. And if there is a dedicated this-tab-only shortcut, then I wouldn't have to worry about settings not being saved (until the next update anyway).

I didn't think of that! Having a keyboard shortcut for this one is way better than using the mouse. I will add a second keyboard shortcut for dimming only the current tab in the next version. Thank you @Andrew15-5 🙏

**Comment by Andrew15-5** [comment]
> I didn't think of that!

I'm assuming this text for the OP flew under your radar:

> or add a second button to **"Dim only this tab"** + **a second shortcut that will do exactly that** would be a blessing

I thought you just didn't want it, since I explicitly added this as a solution.

**Comment by Andrew15-5** [comment]
> Thank you @Andrew15-5

I'm glad that I have a positive impact on the FOSS community and projects. Thank you for this simple yet awesome plugin that is still maintained and open for new features. Not every niche project can do that.

**Comment by mehmetb** [comment]
> I'm assuming this text for the OP flew under your radar:

You're right :/ 

I just created a new version since it is relatively easy to add a new shortcut. It is approved right now so you can update and start using it right away.

**Comment by Andrew15-5** [comment]
One teeny-tiny request. Please change this:

```
Toggle Dim (All tabs): Ctrl + Alt + N (Windows), ⌘ + ⌥ + N (Mac)
Toggle Dim (Active tab only): Ctrl + Alt + B (Windows), ⌘ + ⌥ + B (Mac)
```

To this:

```
Toggle Dim (All tabs): Ctrl + Alt + N (Linux/Windows), ⌘ + ⌥ + N (Mac)
Toggle Dim (Active tab only): Ctrl + Alt + B (Linux/Windows), ⌘ + ⌥ + B (Mac)
```

Linux needs more recognition! And since I happen to use Pop!_OS, it makes me sad that the most popular FOSS platform isn't mentioned, even if it is obviously supported.

**Comment by mehmetb** [comment]
> Linux needs more recognition! And since I happen to use Pop!_OS, it makes me sad that the most popular FOSS platform isn't mentioned, even if it is obviously supported.

You are absolutely right, again! And I used various Linux distros for 5+ years as my primary OS; I'm ashamed of myself right now 😔 

Updated README, the add-on page, and the add-on release notes accordingly 👍

**Comment by Andrew15-5** [comment]
So you **are** a fellow Linux user? Great! Thank you so much for all that you've done!
