### ISSUE TITLE
Add toggled by default and remember opacity level

### ISSUE THREAD

**Issue by Guilouf** [mehmetb/dimmer#6]
I had a hard finding a good firefox extension for controlling brightness without messing the style, and this one does a great job.

However, i had to enable it on every page i visit, and reset the suited opacity everytime.
If only there was a global 'enable' or 'disable' button that will work globaly, and a persistent setting for opacity level, this extension would be perfect in my eyes.

I would have submitted a PR but i don't know much about writting browser extension for now

**Comment by mehmetb** [comment]
Hi @Guilouf, this feature is now available with the version 3. Thank you for the idea :)

**Comment by Guilouf** [comment]
@mehmetb Great ! The 'only for this tab' option is also a good idea.
